baseURL = 'http://localhost:1313/'
languageCode = 'nl-NL'
defaultContentLanguage = "nl"
defaultContentLang = "nl"
title = 'Fijt & Fictie'
theme = "fijtTheme"
enableRobotsTXT = true

[taxonomies]
    auteur = "auteurs"

[params]
    logoLocation = '/fijt_fictie.svg'
    logoAlternative = 'Fijt & Fictie'
    headline = 'Het Nieuw Rotterdamsch Cabaret'